import Head from 'next/head'
import Image from 'next/image'
import { Text, Box, Container, Flex } from '@chakra-ui/react'
import { motion } from 'framer-motion'
import HomePage from '../components/layout/HomePage'
import BioHome from '../components/layout/BioHome'

const sentence = {
  hidden: {opacity: 1},
  visible: {
    opacity: 1,
    transition: {
      delay: 0.8,
      staggerChildren: 0.2
    }
  },
}

const letter = {
  hidden: {opacity: 0, y: 50},
  visible: {
    opacity: 1,
    y: 0
  },
}

export default function Home() {
  const line = "Hi, I'm Bekim"

  return (
    // <Container>
    //   <Head>
    //     <title>Bekim Sinanovic</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

    //   <Box display='flex' justifyContent='center' alignItems='center'>
    //     <Text>
    //       Hi, I&apos;m Bekim
    //     </Text>
    //   </Box>
    // </Container>
    // <Flex justifyContent="center" h="80vh" alignItems="center" fontSize={50}>
    //   <motion.h3
    //     className='load-screen--message'
    //     variants={sentence}
    //     initial="hidden"
    //     animate="visible"
    //   >
    //     {line.split(" ").map((char, index) => {
    //       return (
    //         <motion.span key={char + "-" + index} variants={letter}>
    //           {char + " "}
    //         </motion.span>
    //       )
    //     })}
    //   </motion.h3>
    // </Flex>
    <HomePage />
  )
}
