import Head from 'next/head'
import Image from 'next/image'
import { Text, Box, Container } from '@chakra-ui/react'

export default function Home() {
  return (
    <Container>
      {/* <Head>
        <title>Bekim Sinanovic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <Box display='flex' justifyContent='center' alignItems='center'
      // as='video'
      // controls

      >
        <Text>
          Hi, I&apos;m Bekim
        </Text>
      </Box>
    </Container>
  )
}
